# Import Library

In [1]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import pandas as pd
import os

# Connect Postgres Database

In [3]:
load_dotenv()

DB_STRING = os.getenv("DB_STRING")

if DB_STRING is None:
    raise ValueError("DB_STRING is not set in the environment.")

db = create_engine(DB_STRING)

# Check for DB Connection

In [4]:
print(db)

Engine(postgresql://aieng_onl_en_290626_honey_layers:***@ds-sql-playground.c8g8r1deus2v.eu-central-1.rds.amazonaws.com:5432/postgres)

# Run SQL Query for getting the relevant Data for the Client

In [5]:
query = """
SET SCHEMA 'eda';

WITH zipcode_medians AS (
    SELECT
        zipcode,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY price) AS median_price
    FROM king_county_house_details d
    JOIN king_county_house_sales s ON d.id = s.house_id
    GROUP BY zipcode
),
zipcode_ranked AS (
    SELECT
        zipcode,
        median_price,
        PERCENT_RANK() OVER (ORDER BY median_price) AS price_percentile
    FROM zipcode_medians
),
middle_class_zips AS (
    SELECT zipcode FROM zipcode_ranked
    WHERE price_percentile BETWEEN 0.4 AND 0.6
)
SELECT
    d.*,
    s.date,
    s.price,
    COUNT(s.house_id) OVER (PARTITION BY d.id) AS sale_count
FROM king_county_house_details d
LEFT JOIN king_county_house_sales s ON d.id = s.house_id
WHERE d.zipcode IN (SELECT zipcode FROM middle_class_zips)
ORDER BY d.zipcode, d.id;
"""

df = pd.read_sql(query, db)

# Check the Dataframe

In [8]:
print(df.shape)
df.head()

(3818, 22)

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,date,price,sale_count
0,200500410,3.0,2.5,1960.0,9535.0,2.0,0.0,0.0,3,8,...,1989,NaN,98011,47.7371,-122.215,2520.0,9206.0,2015-05-06,575000.0,1
1,200500610,3.0,2.5,2600.0,7465.0,2.0,0.0,0.0,3,9,...,1988,NaN,98011,47.7387,-122.217,2660.0,7683.0,2014-06-11,571000.0,1
2,200500680,3.0,2.5,2620.0,11056.0,2.0,0.0,0.0,3,9,...,1988,0.0,98011,47.7378,-122.218,2560.0,8688.0,2014-07-15,557500.0,1
3,200500700,3.0,2.5,2120.0,9736.0,2.0,0.0,0.0,3,9,...,1988,NaN,98011,47.7374,-122.219,2490.0,8763.0,2014-06-12,531000.0,1
4,200510060,3.0,2.5,2570.0,9487.0,2.0,0.0,3.0,3,9,...,1989,0.0,98011,47.7408,-122.216,2490.0,9898.0,2014-12-31,605000.0,1

In [9]:
df[df["sale_count"] > 1]

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,date,price,sale_count
13,526059224,4.0,1.75,1650.0,7276.0,1.0,0.0,0.0,3,7,...,1977,0.0,98011,47.7721,-122.206,1840.0,8550.0,2014-09-23,260000.0,2
14,526059224,4.0,1.75,1650.0,7276.0,1.0,0.0,0.0,3,7,...,1977,0.0,98011,47.7721,-122.206,1840.0,8550.0,2015-02-06,470000.0,2
293,8161020060,4.0,2.50,2040.0,21781.0,2.0,0.0,0.0,3,8,...,1994,0.0,98014,47.6458,-121.904,2410.0,21781.0,2015-04-14,471000.0,2
294,8161020060,4.0,2.50,2040.0,21781.0,2.0,0.0,0.0,3,8,...,1994,0.0,98014,47.6458,-121.904,2410.0,21781.0,2014-06-20,443500.0,2
527,1524079093,3.0,1.75,1300.0,20700.0,1.0,0.0,0.0,3,7,...,1962,NaN,98024,47.5587,-121.904,1930.0,37638.0,2014-08-27,275000.0,2
528,1524079093,3.0,1.75,1300.0,20700.0,1.0,0.0,0.0,3,7,...,1962,NaN,98024,47.5587,-121.904,1930.0,37638.0,2015-03-18,369500.0,2
851,8832900780,5.0,2.00,1760.0,21562.0,1.0,0.0,1.0,3,8,...,1959,0.0,98028,47.7597,-122.263,2150.0,12676.0,2014-10-13,480000.0,2
852,8832900780,5.0,2.00,1760.0,21562.0,1.0,0.0,1.0,3,8,...,1959,0.0,98028,47.7597,-122.263,2150.0,12676.0,2015-04-08,647500.0,2
961,1974300020,4.0,2.50,2270.0,11500.0,1.0,0.0,0.0,3,8,...,1967,0.0,98034,47.7089,-122.241,2020.0,10918.0,2015-02-18,624900.0,2
962,1974300020,4.0,2.50,2270.0,11500.0,1.0,0.0,0.0,3,8,...,1967,0.0,98034,47.7089,-122.241,2020.0,10918.0,2014-08-27,380000.0,2
1100,3558900590,6.0,1.75,2230.0,10080.0,1.0,0.0,0.0,3,7,...,1969,0.0,98034,47.7089,-122.201,2110.0,8475.0,2014-11-25,360000.0,2
1101,3558900590,6.0,1.75,2230.0,10080.0,1.0,0.0,0.0,3,7,...,1969,0.0,98034,47.7089,-122.201,2110.0,8475.0,2015-03-24,692500.0,2
1579,8564860270,4.0,2.50,2680.0,5539.0,2.0,NaN,0.0,3,8,...,2013,0.0,98045,47.4759,-121.734,2680.0,5992.0,2015-03-30,502000.0,2
1580,8564860270,4.0,2.50,2680.0,5539.0,2.0,NaN,0.0,3,8,...,2013,0.0,98045,47.4759,-121.734,2680.0,5992.0,2014-07-08,449990.0,2
1627,9407110710,3.0,1.75,1510.0,8400.0,1.0,0.0,0.0,2,7,...,1979,0.0,98045,47.4476,-121.771,1500.0,10125.0,2014-11-07,195000.0,2
1628,9407110710,3.0,1.75,1510.0,8400.0,1.0,0.0,0.0,2,7,...,1979,0.0,98045,47.4476,-121.771,1500.0,10125.0,2015-02-26,322000.0,2
1933,5127001320,3.0,1.75,1520.0,9600.0,1.0,NaN,0.0,4,7,...,1967,0.0,98059,47.4730,-122.149,1590.0,10183.0,2014-11-25,190000.0,2
1934,5127001320,3.0,1.75,1520.0,9600.0,1.0,NaN,0.0,4,7,...,1967,0.0,98059,47.4730,-122.149,1590.0,10183.0,2015-02-23,314950.0,2
2012,7230400400,3.0,2.00,1220.0,17652.0,1.0,0.0,0.0,4,7,...,1980,0.0,98059,47.4712,-122.100,1990.0,17652.0,2014-09-26,240000.0,2
2013,7230400400,3.0,2.00,1220.0,17652.0,1.0,0.0,0.0,4,7,...,1980,0.0,98059,47.4712,-122.100,1990.0,17652.0,2015-03-26,415500.0,2
2088,9353300600,3.0,1.50,1360.0,10726.0,1.0,0.0,0.0,4,7,...,1966,0.0,98059,47.4948,-122.134,1650.0,10726.0,2015-03-26,370000.0,2
2089,9353300600,3.0,1.50,1360.0,10726.0,1.0,0.0,0.0,4,7,...,1966,0.0,98059,47.4948,-122.134,1650.0,10726.0,2014-06-24,348500.0,2
2135,5417600130,2.0,1.00,910.0,9000.0,1.0,NaN,0.0,3,5,...,1923,0.0,98065,47.5260,-121.810,1290.0,9000.0,2014-10-10,244500.0,2
2136,5417600130,2.0,1.00,910.0,9000.0,1.0,NaN,0.0,3,5,...,1923,0.0,98065,47.5260,-121.810,1290.0,9000.0,2015-05-12,301000.0,2
2398,7853400250,4.0,3.50,2910.0,5260.0,2.0,0.0,0.0,3,9,...,2012,0.0,98065,47.5168,-121.883,2910.0,5260.0,2014-06-04,610000.0,2
2399,7853400250,4.0,3.50,2910.0,5260.0,2.0,0.0,0.0,3,9,...,2012,0.0,98065,47.5168,-121.883,2910.0,5260.0,2015-02-19,645000.0,2
2403,7853420110,3.0,3.00,2780.0,6000.0,2.0,0.0,0.0,3,9,...,2013,0.0,98065,47.5184,-121.886,2850.0,6000.0,2014-10-03,594866.0,2
2404,7853420110,3.0,3.00,2780.0,6000.0,2.0,0.0,0.0,3,9,...,2013,0.0,98065,47.5184,-121.886,2850.0,6000.0,2015-05-04,625000.0,2
2422,722039087,2.0,1.00,990.0,57499.0,1.0,0.0,0.0,2,6,...,1949,0.0,98070,47.4145,-122.463,2090.0,27442.0,2014-09-23,220500.0,2
2423,722039087,2.0,1.00,990.0,57499.0,1.0,0.0,0.0,2,6,...,1949,0.0,98070,47.4145,-122.463,2090.0,27442.0,2015-05-04,329000.0,2
2766,9238500040,3.0,2.50,2970.0,23100.0,1.0,0.0,0.0,3,7,...,1967,0.0,98072,47.7735,-122.133,2390.0,20300.0,2014-06-24,400000.0,2
2767,9238500040,3.0,2.50,2970.0,23100.0,1.0,0.0,0.0,3,7,...,1967,0.0,98072,47.7735,-122.133,2390.0,20300.0,2015-02-10,599000.0,2
2876,2044500213,4.0,2.00,1870.0,6000.0,1.5,0.0,0.0,3,7,...,1956,NaN,98125,47.7155,-122.315,1520.0,7169.0,2015-01-26,449000.0,2
2877,2044500213,4.0,2.00,1870.0,6000.0,1.5,0.0,0.0,3,7,...,1956,NaN,98125,47.7155,-122.315,1520.0,7169.0,2014-06-17,310000.0,2
2890,2568300045,6.0,2.00,1900.0,8240.0,1.0,0.0,0.0,2,7,...,1964,NaN,98125,47.7037,-122.296,1900.0,8240.0,2014-06-25,305000.0,2
2891,2568300045,6.0,2.00,1900.0,8240.0,1.0,0.0,0.0,2,7,...,1964,NaN,98125,47.7037,-122.296,1900.0,8240.0,2015-03-19,649950.0,2
2899,2726049071,2.0,1.00,820.0,4206.0,1.0,0.0,0.0,3,5,...,1949,NaN,98125,47.7076,-122.284,1810.0,7200.0,2014-12-11,510000.0,2
2900,2726049071,2.0,1.00,820.0,4206.0,1.0,0.0,0.0,3,5,...,1949,NaN,98125,47.7076,-122.284,1810.0,7200.0,2015-04-08,489950.0,2
2968,3935900232,3.0,1.00,920.0,5546.0,1.0,0.0,0.0,2,6,...,1928,0.0,98125,47.7114,-122.284,1300.0,5546.0,2014-09-29,207000.0,2
2969,3935900232,3.0,1.00,920.0,5546.0,1.0,0.0,0.0,2,6,...,1928,0.0,98125,47.7114,-122.284,1300.0,5546.0,2015-01-12,237000.0,2
3019,5101405604,1.0,1.00,900.0,6380.0,1.0,NaN,0.0,3,6,...,1947,0.0,98125,47.7019,-122.311,1830.0,6380.0,2014-08-14,350000.0,2
3020,5101405604,1.0,1.00,900.0,6380.0,1.0,NaN,0.0,3,6,...,1947,0.0,98125,47.7019,-122.311,1830.0,6380.0,2015-04-28,395000.0,2
3058,6381500170,2.0,1.00,910.0,7617.0,1.0,0.0,0.0,3,6,...,1936,0.0,98125,47.7332,-122.305,1310.0,6624.0,2014-08-26,235000.0,2
3059,6381500170,2.0,1.00,910.0,7617.0,1.0,0.0,0.0,3,6,...,1936,0.0,98125,47.7332,-122.305,1310.0,6624.0,2015-01-16,365000.0,2
3159,8820903380,6.0,2.25,2660.0,13579.0,2.0,0.0,0.0,3,7,...,1937,19900.0,98125,47.7142,-122.286,1120.0,8242.0,2015-01-02,730000.0,2
3160,8820903380,6.0,2.25,2660.0,13579.0,2.0,0.0,0.0,3,7,...,1937,19900.0,98125,47.7142,-122.286,1120.0,8242.0,2014-07-28,452000.0,2
3536,1250201165,5.0,2.50,2000.0,3600.0,1.0,0.0,0.0,3,6,...,1987,0.0,98144,47.5971,-122.295,1410.0,3600.0,2015-03-17,474500.0,2
3537,1250201165,5.0,2.50,2000.0,3600.0,1.0,0.0,0.0,3,6,...,1987,0.0,98144,47.5971,-122.295,1410.0,3600.0,2014-11-21,441000.0,2
3797,9834200305,3.0,1.00,1790.0,3876.0,1.5,0.0,0.0,5,7,...,1904,0.0,98144,47.5750,-122.288,1360.0,4080.0,2015-02-10,615000.0,2
3798,9834200305,3.0,1.00,1790.0,3876.0,1.5,0.0,0.0,5,7,...,1904,0.0,98144,47.5750,-122.288,1360.0,4080.0,2014-07-16,350000.0,2
3804,9834200885,4.0,2.50,2080.0,4080.0,1.0,0.0,0.0,5,7,...,1962,0.0,98144,47.5720,-122.290,1340.0,4080.0,2015-04-20,550000.0,2
3805,9834200885,4.0,2.50,2080.0,4080.0,1.0,0.0,0.0,5,7,...,1962,0.0,98144,47.5720,-122.290,1340.0,4080.0,2014-07-17,360000.0,2

# Save the data in a CSV file

In [11]:
df.to_csv("data/bonnie_brown_middle_class_houses.csv", index=False)